#!/usr/bin/env python3
"""Convert TLG-023 course track map JSON to human-readable Markdown."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def _fmt_list(values: list[str]) -> str:
    return ", ".join(values) if values else "無"


def _fmt_nullable(value: Any) -> str:
    return value if value else "無"


def json_to_markdown(input_path: Path, output_path: Path) -> None:
    data = json.loads(input_path.read_text(encoding="utf-8"))
    lessons = sorted(data["lessons"], key=lambda x: x["sequence_no"])

    lines: list[str] = []
    lines.append(f"# {data['target_lang'].upper()} {data['level']} Dual-Track Course Map v1 (Human-Readable)")
    lines.append("")
    lines.append(f"Source JSON: `{input_path.name}`")
    lines.append("")
    lines.append("> Auto-generated. Do not edit this file directly. Edit JSON then regenerate.")
    lines.append("")

    if "maintenance_note" in data:
        note = data["maintenance_note"]
        lines.append("## Sync Policy")
        lines.append("")
        lines.append(f"- zh_tw: {note['sync_rule_zh_tw']}")
        lines.append(f"- en: {note['sync_rule_en']}")
        lines.append(f"- command: `{note['markdown_generator_command']}`")
        lines.append("")

    lines.append("## 1) 課程總覽")
    lines.append("")
    lines.append("| Seq | Lesson ID | 類型 | 主題 | 主要目標 |")
    lines.append("| --- | --- | --- | --- | --- |")
    for lesson in lessons:
        track = "功能課" if lesson["track_type"] == "functional" else "文法課"
        lines.append(
            f"| {lesson['sequence_no']} | {lesson['lesson_id']} | {track} | "
            f"{lesson['title_zh_tw']} | {lesson['primary_objective_id']} |"
        )

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 2) 每課重點")
    lines.append("")
    for lesson in lessons:
        track = "功能課" if lesson["track_type"] == "functional" else "文法課"
        lines.append(f"### {lesson['lesson_id']}（{track}）")
        lines.append(f"- 主目標: {lesson['primary_objective_id']}")
        lines.append(f"- 次目標: {_fmt_list(lesson['secondary_objective_ids'])}")
        lines.append(f"- 情境: {_fmt_list(lesson['context_ids'])}")
        lines.append(f"- 核心句型: {_fmt_list(lesson['pattern_ids'])}")
        lines.append(f"- 核心文法: {_fmt_list(lesson['grammar_ids'])}")
        lines.append(f"- 對應功能: {_fmt_list(lesson['function_ids'])}")
        lines.append(f"- 先修: {_fmt_list(lesson['prerequisites'])}")
        lines.append("- 學完建議:")
        lines.append(
            f"  - 功能課: {_fmt_nullable(lesson['bridge_to_track']['recommended_next_functional_lesson_id'])}"
        )
        lines.append(
            f"  - 文法課: {_fmt_nullable(lesson['bridge_to_track']['recommended_next_grammar_lesson_id'])}"
        )
        lines.append(f"- Bridge 註記: {lesson['bridge_to_track']['bridge_note_zh_tw']}")
        lines.append(
            f"- Node 配置: min={lesson['node_profile']['min_nodes']}, "
            f"max={lesson['node_profile']['max_nodes']}, "
            f"required={_fmt_list(lesson['node_profile']['required_node_types'])}, "
            f"anchor={lesson['node_profile']['must_include_anchor']}"
        )
        lines.append("")

    output_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="TLG-023 course track map codec")
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("json-to-md", help="Render markdown from JSON")
    p.add_argument("--input", required=True)
    p.add_argument("--output", required=True)

    args = parser.parse_args()
    if args.command == "json-to-md":
        json_to_markdown(Path(args.input), Path(args.output))


if __name__ == "__main__":
    main()
